// <auto-generated />
using System;
using CustomerPartsTracker.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CustomerPartsTracker.Server.Migrations
{
    [DbContext(typeof(CustomerPartsTrackerContext))]
    [Migration("20210505063154_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CustomerPartsTracker.Shared.Models.Customer", b =>
                {
                    b.Property<short>("CustomerId")
                        .HasColumnType("smallint")
                        .HasColumnName("CustomerId");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(65)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(65)");

                    b.HasKey("CustomerId")
                        .HasName("PK_CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("CustomerPartsTracker.Shared.Models.Part", b =>
                {
                    b.Property<short>("PartId")
                        .HasColumnType("smallint")
                        .HasColumnName("PartId");

                    b.Property<short>("CustomerId")
                        .HasColumnType("smallint")
                        .HasColumnName("CustomerId");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasMaxLength(65)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(65)");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("PartId")
                        .HasName("PK_PartId");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("CustomerPartsTracker.Shared.Models.Tracker", b =>
                {
                    b.Property<short>("TrackingId")
                        .HasColumnType("smallint")
                        .HasColumnName("TrackingId");

                    b.Property<string>("Comments")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Comments");

                    b.Property<short>("CustomerId")
                        .HasColumnType("smallint")
                        .HasColumnName("CustomerId");

                    b.Property<string>("LotNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("LotNo");

                    b.Property<short>("PartId")
                        .HasColumnType("smallint")
                        .HasColumnName("PartId");

                    b.Property<string>("PoNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("PoNo");

                    b.Property<string>("ProjectNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ProjectNo");

                    b.Property<string>("QaNote")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("QaNote");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("date");

                    b.Property<string>("SecondaryId")
                        .HasMaxLength(25)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("SecondaryId");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("SerialNumber");

                    b.Property<DateTime?>("ShippedDate")
                        .HasColumnType("date");

                    b.HasKey("TrackingId")
                        .HasName("PK__Trackers");

                    b.ToTable("Trackers");
                });
#pragma warning restore 612, 618
        }
    }
}
